networks:
  basic:

services:

  ca.orderer.healthcare.com:
    container_name: ca.orderer.healthcare.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.orderer.healthcare.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/ca.orderer.healthcare.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - 7020:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${ORDERER_CA_ADMIN_NAME}:${ORDERER_CA_ADMIN_PASSWORD} -d'
    volumes:
      - ../fabric-config/crypto-config/peerOrganizations/orderer.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server/crypto
      - ../fabric-config/fabric-ca-server-config/orderer.healthcare.com/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - basic

  cli.orderer.healthcare.com:
    container_name: cli.orderer.healthcare.com
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - CORE_PEER_ID=cli.orderer.healthcare.com
      - CORE_CHAINCODE_KEEPALIVE=10
      #
      - CORE_PEER_LOCALMSPID=OrdererMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/cli/crypto/users/Admin@orderer.healthcare.com/msp
    working_dir: /var/hyperledger/cli/
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-docker/scripts/cli:/var/hyperledger/cli/scripts/
      - ../fabric-config/config:/var/hyperledger/cli/config/ # genesis.block and channel.tx's
      - ../fabric-config/crypto-config/peerOrganizations/orderer.healthcare.com:/var/hyperledger/cli/crypto/
      - ../fabric-config/chaincode-packages:/var/hyperledger/cli/chaincode-packages/
      - "$CHAINCODES_BASE_DIR/./chaincodes/patient/:/var/hyperledger/cli/patientcc/"
    networks:
      - basic

  fablo-rest.orderer.healthcare.com:
    container_name: fablo-rest.orderer.healthcare.com
    image: ghcr.io/fablo-io/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=OrdererMSP
      - FABRIC_CA_URL=http://ca.orderer.healthcare.com:7054
      - FABRIC_CA_NAME=ca.orderer.healthcare.com
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpc://peer0.doctor.healthcare.com:7041,grpc://peer0.patient.healthcare.com:7061
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    ports:
      - 8800:8000
    networks:
      - basic

  orderer0.group1.orderer.healthcare.com:
    container_name: orderer0.group1.orderer.healthcare.com
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7030
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # Genesis file configuration (for solo and raft)
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/config/Group1Genesis.block
      # Metrics configuration
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer0.group1.orderer.healthcare.com:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /var/hyperledger/orderer
    command: orderer
    ports:
      - 7030:7030
      - 8030:9440
    volumes:
      - ../fabric-config/config/:/var/hyperledger/config
      - ../fabric-config/crypto-config/peerOrganizations/orderer.healthcare.com/peers/orderer0.group1.orderer.healthcare.com/msp/:/var/hyperledger/orderer/msp
      - ../fabric-config/crypto-config/peerOrganizations/orderer.healthcare.com/peers/orderer0.group1.orderer.healthcare.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - basic

  ca.doctor.healthcare.com:
    container_name: ca.doctor.healthcare.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.doctor.healthcare.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/ca.doctor.healthcare.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - 7040:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${DOCTOR_CA_ADMIN_NAME}:${DOCTOR_CA_ADMIN_PASSWORD} -d'
    volumes:
      - ../fabric-config/crypto-config/peerOrganizations/doctor.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server/crypto
      - ../fabric-config/fabric-ca-server-config/doctor.healthcare.com/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - basic

  cli.doctor.healthcare.com:
    container_name: cli.doctor.healthcare.com
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - CORE_PEER_ID=cli.doctor.healthcare.com
      - CORE_CHAINCODE_KEEPALIVE=10
      #
      - CORE_PEER_LOCALMSPID=DoctorMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/cli/crypto/users/Admin@doctor.healthcare.com/msp
      - CORE_PEER_ADDRESS=peer0.doctor.healthcare.com:7041
    working_dir: /var/hyperledger/cli/
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-docker/scripts/cli:/var/hyperledger/cli/scripts/
      - ../fabric-config/config:/var/hyperledger/cli/config/ # genesis.block and channel.tx's
      - ../fabric-config/crypto-config/peerOrganizations/doctor.healthcare.com:/var/hyperledger/cli/crypto/
      - ../fabric-config/chaincode-packages:/var/hyperledger/cli/chaincode-packages/
      - "$CHAINCODES_BASE_DIR/./chaincodes/patient/:/var/hyperledger/cli/patientcc/"
    networks:
      - basic

  fablo-rest.doctor.healthcare.com:
    container_name: fablo-rest.doctor.healthcare.com
    image: ghcr.io/fablo-io/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=DoctorMSP
      - FABRIC_CA_URL=http://ca.doctor.healthcare.com:7054
      - FABRIC_CA_NAME=ca.doctor.healthcare.com
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpc://peer0.doctor.healthcare.com:7041,grpc://peer0.patient.healthcare.com:7061
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    ports:
      - 8801:8000
    networks:
      - basic

  peer0.doctor.healthcare.com:
    container_name: peer0.doctor.healthcare.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=DoctorMSP
      - CORE_PEER_ID=peer0.doctor.healthcare.com
      - CORE_PEER_ADDRESS=peer0.doctor.healthcare.com:7041
      - CORE_PEER_LISTENADDRESS=peer0.doctor.healthcare.com:7041
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.doctor.healthcare.com:7041
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.doctor.healthcare.com:7041
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.doctor.healthcare.com:7041
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.doctor.healthcare.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:${FABRIC_NODEENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer0.doctor.healthcare.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
      # enabled gateway
      - CORE_PEER_GATEWAY_ENABLED=true
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8041:9440
      - 7041:7041
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/doctor.healthcare.com/peers/peer0.doctor.healthcare.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/doctor.healthcare.com/peers/peer0.doctor.healthcare.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/doctor.healthcare.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic

  ca.patient.healthcare.com:
    container_name: ca.patient.healthcare.com
    image: hyperledger/fabric-ca:${FABRIC_CA_VERSION}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.patient.healthcare.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/crypto/ca.patient.healthcare.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/crypto/priv-key.pem
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
    ports:
      - 7060:7054
    working_dir: /etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b ${PATIENT_CA_ADMIN_NAME}:${PATIENT_CA_ADMIN_PASSWORD} -d'
    volumes:
      - ../fabric-config/crypto-config/peerOrganizations/patient.healthcare.com/ca/:/etc/hyperledger/fabric-ca-server/crypto
      - ../fabric-config/fabric-ca-server-config/patient.healthcare.com/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    networks:
      - basic

  cli.patient.healthcare.com:
    container_name: cli.patient.healthcare.com
    image: hyperledger/fabric-tools:${FABRIC_TOOLS_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      - CORE_PEER_ID=cli.patient.healthcare.com
      - CORE_CHAINCODE_KEEPALIVE=10
      #
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/cli/crypto/users/Admin@patient.healthcare.com/msp
      - CORE_PEER_ADDRESS=peer0.patient.healthcare.com:7061
    working_dir: /var/hyperledger/cli/
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-docker/scripts/cli:/var/hyperledger/cli/scripts/
      - ../fabric-config/config:/var/hyperledger/cli/config/ # genesis.block and channel.tx's
      - ../fabric-config/crypto-config/peerOrganizations/patient.healthcare.com:/var/hyperledger/cli/crypto/
      - ../fabric-config/chaincode-packages:/var/hyperledger/cli/chaincode-packages/
      - "$CHAINCODES_BASE_DIR/./chaincodes/patient/:/var/hyperledger/cli/patientcc/"
    networks:
      - basic

  fablo-rest.patient.healthcare.com:
    container_name: fablo-rest.patient.healthcare.com
    image: ghcr.io/fablo-io/fablo-rest:${FABLO_REST_VERSION}
    environment:
      - PORT=8000
      - MSP_ID=PatientMSP
      - FABRIC_CA_URL=http://ca.patient.healthcare.com:7054
      - FABRIC_CA_NAME=ca.patient.healthcare.com
      - AS_LOCALHOST=false
      - DISCOVERY_URLS=grpc://peer0.doctor.healthcare.com:7041,grpc://peer0.patient.healthcare.com:7061
      - HFC_LOGGING={"error":"console","warn":"console","info":"console"}
    ports:
      - 8802:8000
    networks:
      - basic

  peer0.patient.healthcare.com:
    container_name: peer0.patient.healthcare.com
    image: hyperledger/fabric-peer:${FABRIC_VERSION}
    environment:
      - CORE_PEER_LOCALMSPID=PatientMSP
      - CORE_PEER_ID=peer0.patient.healthcare.com
      - CORE_PEER_ADDRESS=peer0.patient.healthcare.com:7061
      - CORE_PEER_LISTENADDRESS=peer0.patient.healthcare.com:7061
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.patient.healthcare.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.healthcare.com:7061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.healthcare.com:7061
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.patient.healthcare.com:7050
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/msp
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:${FABRIC_CCENV_VERSION}
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:${FABRIC_BASEOS_VERSION}
      - CORE_CHAINCODE_JAVA_RUNTIME=hyperledger/fabric-javaenv:${FABRIC_JAVAENV_VERSION}
      - CORE_CHAINCODE_NODE_RUNTIME=hyperledger/fabric-nodeenv:${FABRIC_NODEENV_VERSION}
      #
      - CORE_CHAINCODE_LOGGING_LEVEL=${LOGGING_LEVEL}
      - CORE_CHAINCODE_LOGGING_SHIM=${LOGGING_LEVEL}
      - FABRIC_LOGGING_SPEC=${LOGGING_LEVEL}
      # metrics
      - CORE_OPERATIONS_LISTENADDRESS=peer0.patient.healthcare.com:9440
      - CORE_METRICS_PROVIDER=prometheus
      #
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - GODEBUG=netdns=go
      # enabled gateway
      - CORE_PEER_GATEWAY_ENABLED=true
    working_dir: /etc/hyperledger/fabric/peer/
    command: peer node start
    ports:
      - 8061:9440
      - 7061:7061
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../fabric-config/crypto-config/peerOrganizations/patient.healthcare.com/peers/peer0.patient.healthcare.com/msp:/etc/hyperledger/fabric/peer/msp
      - ../fabric-config/crypto-config/peerOrganizations/patient.healthcare.com/peers/peer0.patient.healthcare.com/tls:/etc/hyperledger/fabric/peer/tls
      - ../fabric-config/crypto-config/peerOrganizations/patient.healthcare.com/users:/etc/hyperledger/fabric/peer/msp/users
      - ../fabric-config/config:/etc/hyperledger/fabric/config
    networks:
      - basic
